### ISSUE TITLE
XML Tags - I/O - DocumentExtensions.GetStyle

### ISSUE THREAD

**Issue by mzjensen** [paoloemilioserra/Civil3dToolkit#10]
v1.1.14
Suggest changing the input port label from "item" to "civilObject" to be consistent with similar OOTB nodes.

**Comment by paoloemilioserra** [comment]
Originally it was working on CivilObjects only but it has been extended over time (e.g. COGO Point ro other AutoCAD entities). It will be renamed "obj" for consistency in 1.1.15
