### ISSUE TITLE
XML Tags - I/O - DocumentExtensions.SetStyle

### ISSUE THREAD

**Issue by mzjensen** [paoloemilioserra/Civil3dToolkit#11]
v1.1.14
Suggest changing the input port label from "item" to "civilObject" to be consistent with similar OOTB nodes.

**Comment by paoloemilioserra** [comment]
Initially it worked only on CivilObjects but it it has been extended over time (e.g. COGO Point, Table, ...). It will be renamed "obj" for consistency in 1.1.15
