### ISSUE TITLE
XML Tags - Summary - PolylineExtensions.Offset

### ISSUE THREAD

**Issue by mzjensen** [paoloemilioserra/Civil3dToolkit#27]
v1.1.14
Current: "Creates a Polyline in AutoCAD from a Dynamo PolyCurve"

This appears to be an accidental copy from the _PolylineExtensions.ObjectByGeometry_ node. Suggest changing to be more descriptive for the purpose of this node.

**Comment by paoloemilioserra** [comment]
Proposed "Offsets the Polyline in AutoCAD by the given value."

**Comment by paoloemilioserra** [comment]
fixed in 1.1.15
