### ISSUE TITLE
FeatureLine.PolyCurve - points are likely coincident

### ISSUE THREAD

**Issue by mzjensen** [paoloemilioserra/Civil3dToolkit#31]
v1.1.14

@paoloemilioserra it seems that _FeatureLine.PolyCurve_ does not work correctly when there are arc segments. It returns a polycurve when all of the elevation points are equal, but it returns null when the elevations are different. The log file says that "points are likely coincident".

[Autodesk_Civil3DToolkit.txt](https://github.com/paoloemilioserra/Civil3dToolkit/files/5619525/Autodesk_Civil3DToolkit.txt)
[FeatureLine.PolyCurve.zip](https://github.com/paoloemilioserra/Civil3dToolkit/files/5619527/FeatureLine.PolyCurve.zip)

![FeatureLine PolyCurve](https://user-images.githubusercontent.com/24361762/100683780-e3017300-332d-11eb-9638-e06107caeef3.gif)

**Comment by paoloemilioserra** [comment]
Fixed in 1.1.15 
![image](https://user-images.githubusercontent.com/14221455/100706521-7461fb00-33a9-11eb-8d88-702bb1737773.png)
