### ISSUE TITLE
AlignmentExtensions -> Alignment Types Shelf

### ISSUE THREAD

**Issue by mzjensen** [paoloemilioserra/Civil3dToolkit#35]
v1.1.15
What do you think about moving the Alignment Types selection dropdown to the Civil 3D -> Selection shelf?

**Comment by paoloemilioserra** [comment]
@mzjensen  The Selection nodes are returning an Object, this node instead is a shortcut to avoid to remember the integers associated to the Alignment Type names. I wouldn't change it, thoughts?

**Comment by mzjensen** [comment]
Ah good point. I agree with you.
