### ISSUE TITLE
XML Tags - ProfileExtensions.HighLowPoints - Summary

### ISSUE THREAD

**Issue by mzjensen** [paoloemilioserra/Civil3dToolkit#47]
v1.1.17
Several spelling errors in this string.

Current: "Returns the high and low points elevation and stations **wiht** grade close to zero along **hte** **porfile**"
Suggested: "Returns the elevations and stations for high and low points with grade close to zero along the profile"

**Comment by paoloemilioserra** [comment]
fixed in 1.1.19
