### ISSUE TITLE
Pick Point

### ISSUE THREAD

**Issue by paoloemilioserra** [paoloemilioserra/Civil3dToolkit#52]
A node that allows the user to pick a point in the model space

**Comment by paoloemilioserra** [comment]
Added in 1.1.20

**Comment by ShahidC3D** [comment]
In 1.1.22 

I am getting bellow message for Pick Point node. 
![image](https://user-images.githubusercontent.com/70940000/107786436-ec6a7b00-6d73-11eb-87f8-88840f161559.png)
