### ISSUE TITLE
Add Feature Lines as Corridor Baselines

### ISSUE THREAD

**Issue by 0Tiago** [paoloemilioserra/Civil3dToolkit#55]
Hello Paolo,

Add Feature Lines as Corridor Baselines

By Name, By Selection or By Site

Thank you for your time and efforts

**Comment by paoloemilioserra** [comment]
There is no API at the moment to do that.

**Comment by 0Tiago** [comment]
Thank you for your clarification.

Anyway. this toolkit is brilliant. Fantastic job!!!

**Comment by paoloemilioserra** [comment]
thank you
