### ISSUE TITLE
Civil3dToolkit Nodes

### ISSUE THREAD

**Issue by Mohieb-Nassar** [paoloemilioserra/Civil3dToolkit#56]
Hi Paoleo. 
First of all many thanks for the new updates .

I noticed that you add a node for creating a baseline from Alignment and profile but you didn't add the one that can be done by the Feature lines.
I want to use it to add another regions with different baselines (Feature lines).
the second point its a node to reset the frequency of corridors. 
I want to use it to add more regions and recalculate the frequencies for each region to solve any issues in the shape.

 Regards

**Comment by paoloemilioserra** [comment]
There is no API for featureline based corridors

**Comment by Mohieb-Nassar** [comment]
> There is no API for featureline based corridors

I think you didnt understand my point.
I was asking about a node to do the following steps.
![AAAA](https://user-images.githubusercontent.com/76867171/107147841-a4111e80-6969-11eb-8ab3-f3c130351046.JPG)
![AAA](https://user-images.githubusercontent.com/76867171/107147862-c0ad5680-6969-11eb-9217-9dcbf481415f.JPG)

**Comment by paoloemilioserra** [comment]
I understood correctly, you should have realized that API does not equal what you can do via UI. Also you should have bothered to read the previous entries in the thread as it was just requested yesterday.
