### ISSUE TITLE
AlignmentExtensions.CreateAlignmentPlaceholder - Label Set ID Exception

### ISSUE THREAD

**Issue by mzjensen** [paoloemilioserra/Civil3dToolkit#60]
v.1.1.22

Plugging in a string to the _labelSet_ port causes the node to return null and throw an exception of "Alignment labelSet ID is invalid." It's not a spelling issue because it occurs even when using "Standard" for the label set, which should always work. Log file attached (see line 127).

[Autodesk_Civil3DToolkit.log](https://github.com/paoloemilioserra/Civil3dToolkit/files/5963065/Autodesk_Civil3DToolkit.log)

**Comment by paoloemilioserra** [comment]
good catch, fixed in 1.1.23
