### ISSUE TITLE
Get Profile View Start and End Stations

### ISSUE THREAD

**Issue by mzjensen** [paoloemilioserra/Civil3dToolkit#65]
This would be a helpful addition to the ProfileView shelf. I had to write a Python node to do this because I was needing to determine the profile view that corresponded with objects along an alignment. Pretty simple with the StationStart and StationEnd properties.

https://help.autodesk.com/view/CIV3D/2020/ENU/?guid=c800936e-0cb5-8d83-b6c4-416f8d88f59d
https://help.autodesk.com/view/CIV3D/2020/ENU/?guid=f01dfc33-f218-e36d-6f83-8a008bc9966d

**Comment by paoloemilioserra** [comment]
Added Get and Set Start/End stations in 1.1.23
