### ISSUE TITLE
Request for New Node - SetCoordinateSystemCode

### ISSUE THREAD

**Issue by cstcarmo** [paoloemilioserra/Civil3dToolkit#76]
I would like to ask you one new node similar with GetCoordinateSystemCode, but for setting the CoordinateSystemCode, i.e. SetCoordinateSystemCode. 

Also, the same functionality to change SystemUnits in the drawing.

**Comment by paoloemilioserra** [comment]
Done 
![image](https://user-images.githubusercontent.com/14221455/113441270-4c81b300-93ee-11eb-8d38-1a411ef73950.png)
