### ISSUE TITLE
Pipe.Curve2D

### ISSUE THREAD

**Issue by mzjensen** [paoloemilioserra/Civil3dToolkit#78]
v1.1.22

The _Pipe.Curve2D_ node throws a "SubEntityType is not PipeSubEntityType.Curved" exception. The _Pipe.Curve_ node works correctly. I did not find any info in the log.

![Curve2D](https://user-images.githubusercontent.com/24361762/111494040-5cfe1200-86fb-11eb-8fbd-4fe639bd4c58.JPG)

**Comment by paoloemilioserra** [comment]
Added a check that inspects the subtype and reports it to the Log
