### ISSUE TITLE
SubassemblyTargetInfo.SetTargetsOption - Not Working

### ISSUE THREAD

**Issue by 0Tiago** [paoloemilioserra/Civil3dToolkit#79]
The _SubassemblyTargetInfo.SetTargetsOption does not have any effect when attempting to change the subassembly target potion from nearest to farthest, steepest, or flattest.

Issue screenshot:
![image](https://user-images.githubusercontent.com/78596435/112447627-70d3f480-8d49-11eb-8392-73a7acfd6998.png)

Dynamo Graph:
[Corridors - Set Target Options.zip](https://github.com/paoloemilioserra/Civil3dToolkit/files/6203382/Corridors.-.Set.Target.Options.zip)

Log File:
[Autodesk_Civil3DToolkit (1).txt](https://github.com/paoloemilioserra/Civil3dToolkit/files/6203377/Autodesk_Civil3DToolkit.1.txt)

**Comment by paoloemilioserra** [comment]
I'm looking into this but there is little hope from what I can tell.

**Comment by 0Tiago** [comment]
Okay, thanks for the heads up. Maybe perhaps via Python is accessible and possible to modify?

**Comment by paoloemilioserra** [comment]
there is no difference between Python and Dynamo
