### ISSUE TITLE
OdRecord.SetValueByName setting value in other tables

### ISSUE THREAD

**Issue by jkwon126** [paoloemilioserra/Civil3dToolkit#80]
When an object that has two OD tables attached to it, and ODRecord.SetValueByName is used to set a field value, field values seems to be changed also in the other table.

Screenshot:
![OdRecord SetValueByName](https://user-images.githubusercontent.com/42683919/112695913-1c607000-8e42-11eb-89ba-a46961a742b2.jpg)

Zip of DWG and DYN:
[ODTest.zip](https://github.com/paoloemilioserra/Civil3dToolkit/files/6214498/ODTest.zip)

**Comment by paoloemilioserra** [comment]
Fixed it, thanks

**Comment by jkwon126** [comment]
Thank you for your amazing work, that was a very speedy close.
