### ISSUE TITLE
C12 seems not available in packages 1.1.22

### ISSUE THREAD

**Issue by dytin** [paoloemilioserra/Civil3dToolkit#81]
Hi, I found the C12 in Done list that the set structure size node could set the inner length and width. However, if I changed the length then go to next node for width, the structure size would pick the other length to match width. 

Can I change the length and width simultaneously?

Issue screenshot:
![Screenshot 2021-03-29 121958](https://user-images.githubusercontent.com/79128519/112786561-1dcfa980-9089-11eb-80a2-21fc199c7b52.png)

![Screenshot 2021-03-30 173313](https://user-images.githubusercontent.com/79128519/112967719-22c25500-917e-11eb-9f4f-a12d94af22dd.png)

![Screenshot 2021-03-30 175118](https://user-images.githubusercontent.com/79128519/112970255-949b9e00-9180-11eb-999b-fbeef5618b52.png)

**Comment by paoloemilioserra** [comment]
That's not the issue in the title
