### ISSUE TITLE
OdTable.GetObjectOdRecords pulling records not attached to objects

### ISSUE THREAD

**Issue by jkwon126** [paoloemilioserra/Civil3dToolkit#82]
When OdTable.GetObjectOdRecords is run on an object with a list of tables currently in the drawing, it seems to return records that are not attached to the object.

![GetObjectOdRecords 01](https://user-images.githubusercontent.com/42683919/113656447-c7e29f00-9650-11eb-8a28-5f6f3913ee21.jpg)

![GetObjectOdRecords 02](https://user-images.githubusercontent.com/42683919/113656450-cd3fe980-9650-11eb-96bc-2e0587c8210b.jpg)

Test DWG and DYN used for above screenshots:

[GetObjectOdRecords Test.zip](https://github.com/paoloemilioserra/Civil3dToolkit/files/6261957/GetObjectOdRecords.Test.zip)

p.s. If I am misusing the node, I apologize.

**Comment by paoloemilioserra** [comment]
fixed in 1.1.25
