### ISSUE TITLE
PartFamily By Name node retrieves null

### ISSUE THREAD

**Issue by Mohamed-R-Nasreldeen** [paoloemilioserra/Civil3dToolkit#86]
PartFamily By Name node retrieves null ! I checked many times and I’m sure the family name is correct. According to the description of the node, this works only with Part PIPE Family in the Part List. It seems like it doesn’t work with Part Structure Family.

Civil 3d is updated, civil 3d toolkit is 1.1.24

check the thread here 
[https://forum.dynamobim.com/t/partfamily-by-name-node-retrieves-null/63538](url)

**Comment by paoloemilioserra** [comment]
fixed in 1.1.27
