### ISSUE TITLE
SectionView.Extents ............gives a unhandled exception 

### ISSUE THREAD

**Issue by ShahidC3D** [paoloemilioserra/Civil3dToolkit#89]
![image](https://user-images.githubusercontent.com/70940000/122373565-34e2b100-cf7f-11eb-83de-6e3703a77d55.png)

Getting above message for version 1.1.28
Civil 3D 2020.4

**Comment by mzjensen** [comment]
I got this error too the last time I used it. If you just click 'Arrrrg, ok' and keep going, it seems to work correctly.

**Comment by ShahidC3D** [comment]
sure, but noticed that every time i add a diff node after this nod it pops up again under automatic run condition. tht's little annoying at times.

**Comment by paoloemilioserra** [comment]
@ShahidC3D when the error occurs do you have any log file you can provide? the issue you are experiencing afterwards is with Dynamo and not the Toolkit. I'll close this issue for now.
